---
- name: this playbook creates a file or dir
  hosts: all
  become: true
  tasks:
  - name: copying a file
    copy:
      src: /opt/ansible/index.html
      dest: /home/ansadmin
      owner: john
      mode: 0600 
