---
- name: this playbook install packages
  hosts: dbservers
  become: true
  tasks:
    - name: install packager
      apt:
        name: apache2
        state: present
    
    - name: start apache2 service
      service:
        name: apache2
        state: started

    - name: copy index.html
      copy:
        src: /opt/ansible/index.html
        dest: /var/www/html
        mode: 0666
